In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import csv
import requests

In [2]:
df_data = pd.read_csv('../data/full_data/df_data.csv')
df_data

/tmp/ipykernel_10041/2537818261.py:1: DtypeWarning: Columns (2,9,11,12,16,18,20,21,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df_data = pd.read_csv('../data/full_data/df_data.csv')

,bookId,title,series,author,rating,description,language,isbn,genres,characters,...,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price,Thumbnail,Info Link,Fetched From
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",...,"['3444695', '1921313', '745221', '171994', '93...",96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...,2993816.0,30516.0,5.09,NaN,NaN,NaN
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",...,"['1593642', '637516', '222366', '39573', '14526']",98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...,2632233.0,26923.0,7.38,NaN,NaN,NaN
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9780062369635,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,"['2363896', '1333153', '573280', '149952', '80...",95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...,2269402.0,23328.0,NaN,NaN,NaN,NaN
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,NaN,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",...,"['1617567', '816659', '373311', '113934', '767...",94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...,1983116.0,20452.0,NaN,NaN,NaN,NaN
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Edward Cullen', 'Jacob Black', 'Laurent', 'R...",...,"['1751460', '1113682', '1008686', '542017', '5...",78.0,"['Forks, Washington (United States)', 'Phoenix...",https://i.gr-assets.com/images/S/compressed.ph...,1459448.0,14874.0,2.1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74784,SzxlzgEACAAJ,Afterimage Slow Motion,NaN,Jyanome,NaN,NaN,en,3964335037,nan - yaoi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://books.google.es/books?id=SzxlzgEACAAJ&d...,Google Books
74785,Te04EQAAQBAJ,When Fate Holds Its Breath,NaN,Takiba,NaN,NaN,de,9783551624680,Comics & Graphic Novels - yaoi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=Te04E...,http://books.google.es/books?id=Te04EQAAQBAJ&d...,Google Books
74786,s_8_EAAAQBAJ,Midnight Delivery Sex,NaN,Neneko Narazaki,NaN,Mit SNS-Card zum Sammeln in der ersten Auflage...,de,9783551620668,Comics & Graphic Novels - yaoi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=s_8_E...,http://books.google.es/books?id=s_8_EAAAQBAJ&d...,Google Books
74787,_yjnEAAAQBAJ,Monster Girl: 2,NaN,Kazuki Funatsu,NaN,"Dopo il loro incontro, Yatsuki si ritrova ad a...",it,9788834915899,Comics & Graphic Novels - isekai comedy,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=_yjnE...,http://books.google.es/books?id=_yjnEAAAQBAJ&d...,Google Books
74788,bjZVEAAAQBAJ,La saison du soleil,NaN,Shintaro Ishihara,NaN,"Lauréat du prestigieux prix Akutagawa en 1955,...",fr,9782714497598,Literary Collections - isekai space opera,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://books.google.com/books/content?id=bjZVE...,https://play.google.com/store/books/details?id...,Google Books

In [3]:
columnas_eliminar = ['bbeScore', 'bbeVotes', 'price', 'Thumbnail', 'Info Link', 'Fetched From', 'edition', 'ratingsByStars']
df = df_data.drop(columns=columnas_eliminar)

In [4]:
df

,bookId,title,series,author,rating,description,language,isbn,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",Hardcover,374,Scholastic Press,09/14/08,NaN,['Locus Award Nominee for Best Young Adult Boo...,6376780.0,96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",Paperback,870,Scholastic Inc.,09/28/04,06/21/03,['Bram Stoker Award for Works for Young Reader...,2507623.0,98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9780062369635,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",Paperback,324,Harper Perennial Modern Classics,05/23/06,07/11/60,"['Pulitzer Prize for Fiction (1961)', 'Audie A...",4501075.0,95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,NaN,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",Paperback,279,Modern Library,10/10/00,01/28/13,[],2998241.0,94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Edward Cullen', 'Jacob Black', 'Laurent', 'R...",Paperback,501,"Little, Brown and Company",09/06/06,10/05/05,"['Georgia Peach Book Award (2007)', 'Buxtehude...",4964519.0,78.0,"['Forks, Washington (United States)', 'Phoenix...",https://i.gr-assets.com/images/S/compressed.ph...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74784,SzxlzgEACAAJ,Afterimage Slow Motion,NaN,Jyanome,NaN,NaN,en,3964335037,nan - yaoi,NaN,nan - nan,224.0,NaN,2021-12-02,2021-12-02,NaN,NaN,NaN,NaN,NaN
74785,Te04EQAAQBAJ,When Fate Holds Its Breath,NaN,Takiba,NaN,NaN,de,9783551624680,Comics & Graphic Novels - yaoi,NaN,nan - nan,29.0,NaN,2025,2025,NaN,NaN,NaN,NaN,NaN
74786,s_8_EAAAQBAJ,Midnight Delivery Sex,NaN,Neneko Narazaki,NaN,Mit SNS-Card zum Sammeln in der ersten Auflage...,de,9783551620668,Comics & Graphic Novels - yaoi,NaN,nan - nan,29.0,Hayabusa,2021-05-04,2021-05-04,NaN,NaN,NaN,NaN,NaN
74787,_yjnEAAAQBAJ,Monster Girl: 2,NaN,Kazuki Funatsu,NaN,"Dopo il loro incontro, Yatsuki si ritrova ad a...",it,9788834915899,Comics & Graphic Novels - isekai comedy,NaN,nan - nan,216.0,Edizioni BD,2020-05-01,2020-05-01,NaN,NaN,NaN,NaN,NaN
74788,bjZVEAAAQBAJ,La saison du soleil,NaN,Shintaro Ishihara,NaN,"Lauréat du prestigieux prix Akutagawa en 1955,...",fr,9782714497598,Literary Collections - isekai space opera,NaN,nan - nan,131.0,Belfond,2022-01-27,2022-01-27,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74789 entries, 0 to 74788
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   bookId            74789 non-null  object
 1   title             74789 non-null  object
 2   series            23470 non-null  object
 3   author            74517 non-null  object
 4   rating            53113 non-null  float64
 5   description       71379 non-null  object
 6   language          73542 non-null  object
 7   isbn              74028 non-null  object
 8   genres            74789 non-null  object
 9   characters        52478 non-null  object
 10  bookFormat        73316 non-null  object
 11  pages             73162 non-null  object
 12  publisher         66657 non-null  object
 13  publishDate       74420 non-null  object
 14  firstPublishDate  53463 non-null  object
 15  awards            52478 non-null  object
 16  numRatings        53113 non-null  float64
 17  likedPercent      51856 non-null  float64
 18  setting           52478 non-null  object
 19  coverImg          52096 non-null  object
dtypes: float64(3), object(17)
memory usage: 11.4+ MB

In [6]:
def get_google_books_info(title):
    """Devuelve rating, numRatings, coverImg desde Google Books API."""
    try:
        url = f"https://www.googleapis.com/books/v1/volumes?q=intitle:{title}"
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            if "items" in data and len(data["items"]) > 0:
                volume = data["items"][0]["volumeInfo"]
                return {
                    "rating": volume.get("averageRating"),
                    "numRatings": volume.get("ratingsCount"),
                    "coverImg": volume.get("imageLinks", {}).get("thumbnail"),
                }
    except:
        pass
    return {}

def get_openlibrary_info(title):
    """Devuelve setting, characters, awards desde OpenLibrary API."""
    try:
        url = f"https://openlibrary.org/search.json?title={title}"
        res = requests.get(url)
        if res.status_code == 200:
            data = res.json()
            if data['docs']:
                doc = data['docs'][0]
                return {
                    "setting": ", ".join(doc.get("place", [])) if "place" in doc else None,
                    "characters": ", ".join(doc.get("person", [])) if "person" in doc else None,
                    "awards": ", ".join(doc.get("awards", [])) if "awards" in doc else None,
                }
    except:
        pass
    return {}

# --- RELLENO DE CAMPOS FALTANTES ---

def completar_info_externa(df, max_libros=100):
    procesados = 0

    for idx, row in df.iterrows():
        if procesados >= max_libros:
            break

        title = row['title']
        update_needed = (
            pd.isna(row['rating']) or
            pd.isna(row['numRatings']) or
            pd.isna(row['coverImg']) or
            pd.isna(row['setting']) or
            pd.isna(row['characters']) or
            pd.isna(row['awards'])
        )

        if not update_needed:
            continue

        print(f"Buscando: {title}")
        info_google = get_google_books_info(title)
        info_openlib = get_openlibrary_info(title)

        if pd.isna(row['rating']) and info_google.get('rating') is not None:
            df.at[idx, 'rating'] = info_google['rating']
        if pd.isna(row['numRatings']) and info_google.get('numRatings') is not None:
            df.at[idx, 'numRatings'] = info_google['numRatings']
        if pd.isna(row['coverImg']) and info_google.get('coverImg') is not None:
            df.at[idx, 'coverImg'] = info_google['coverImg']

        if pd.isna(row['setting']) and info_openlib.get('setting') is not None:
            df.at[idx, 'setting'] = info_openlib['setting']
        if pd.isna(row['characters']) and info_openlib.get('characters') is not None:
            df.at[idx, 'characters'] = info_openlib['characters']
        if pd.isna(row['awards']) and info_openlib.get('awards') is not None:
            df.at[idx, 'awards'] = info_openlib['awards']

        procesados += 1
        time.sleep(1.1)  # Evita ser bloqueado por las APIs

    print(f"Completados {procesados} libros.")
    return df

In [7]:
df = completar_info_externa(df, max_libros=74000)

Buscando: The House at Pooh Corner and Now We Are Six

NameError: name 'time' is not defined

In [ ]:
df.to_csv("../data/full_data/libros_completados.csv", index=False)

In [ ]:
df_lc = pd.read_csv('../data/full_data/libros_completados.csv')
df_lc

C:\Users\elena\AppData\Local\Temp\ipykernel_8104\1496375323.py:1: DtypeWarning: Columns (2,9,11,15,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_lc = pd.read_csv('../data/full_data/libros_completados.csv')

,bookId,title,series,author,rating,description,language,isbn,genres,characters,bookFormat,pages,publisher,publishDate,firstPublishDate,awards,numRatings,likedPercent,setting,coverImg
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",Hardcover,374,Scholastic Press,09/14/08,NaN,['Locus Award Nominee for Best Young Adult Boo...,6376780.0,96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",Paperback,870,Scholastic Inc.,09/28/04,06/21/03,['Bram Stoker Award for Works for Young Reader...,2507623.0,98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9780062369635,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",Paperback,324,Harper Perennial Modern Classics,05/23/06,07/11/60,"['Pulitzer Prize for Fiction (1961)', 'Audie A...",4501075.0,95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,NaN,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",Paperback,279,Modern Library,10/10/00,01/28/13,[],2998241.0,94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Edward Cullen', 'Jacob Black', 'Laurent', 'R...",Paperback,501,"Little, Brown and Company",09/06/06,10/05/05,"['Georgia Peach Book Award (2007)', 'Buxtehude...",4964519.0,78.0,"['Forks, Washington (United States)', 'Phoenix...",https://i.gr-assets.com/images/S/compressed.ph...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74784,SzxlzgEACAAJ,Afterimage Slow Motion,NaN,Jyanome,NaN,NaN,en,3964335037,nan - yaoi,NaN,nan - nan,224.0,NaN,2021-12-02,2021-12-02,NaN,NaN,NaN,NaN,NaN
74785,Te04EQAAQBAJ,When Fate Holds Its Breath,NaN,Takiba,NaN,NaN,de,9783551624680,Comics & Graphic Novels - yaoi,NaN,nan - nan,29.0,NaN,2025,2025,NaN,NaN,NaN,NaN,NaN
74786,s_8_EAAAQBAJ,Midnight Delivery Sex,NaN,Neneko Narazaki,NaN,Mit SNS-Card zum Sammeln in der ersten Auflage...,de,9783551620668,Comics & Graphic Novels - yaoi,NaN,nan - nan,29.0,Hayabusa,2021-05-04,2021-05-04,NaN,NaN,NaN,NaN,NaN
74787,_yjnEAAAQBAJ,Monster Girl: 2,NaN,Kazuki Funatsu,NaN,"Dopo il loro incontro, Yatsuki si ritrova ad a...",it,9788834915899,Comics & Graphic Novels - isekai comedy,NaN,nan - nan,216.0,Edizioni BD,2020-05-01,2020-05-01,NaN,NaN,NaN,NaN,NaN
74788,bjZVEAAAQBAJ,La saison du soleil,NaN,Shintaro Ishihara,NaN,"Lauréat du prestigieux prix Akutagawa en 1955,...",fr,9782714497598,Literary Collections - isekai space opera,NaN,nan - nan,131.0,Belfond,2022-01-27,2022-01-27,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_lc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74789 entries, 0 to 74788
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   bookId            74789 non-null  object
 1   title             74789 non-null  object
 2   series            23470 non-null  object
 3   author            74517 non-null  object
 4   rating            53582 non-null  float64
 5   description       71379 non-null  object
 6   language          73542 non-null  object
 7   isbn              74028 non-null  object
 8   genres            74789 non-null  object
 9   characters        52478 non-null  object
 10  bookFormat        73316 non-null  object
 11  pages             73162 non-null  object
 12  publisher         66657 non-null  object
 13  publishDate       74420 non-null  object
 14  firstPublishDate  53463 non-null  object
 15  awards            52478 non-null  object
 16  numRatings        53582 non-null  float64
 17  likedPercent      51856 non-null  float64
 18  setting           52478 non-null  object
 19  coverImg          65676 non-null  object
dtypes: float64(3), object(17)
memory usage: 11.4+ MB